### ISSUE TITLE
not so useful like this

### ISSUE THREAD

**Issue by sjatkins** [jhh/netscape-bookmark-converter#3]
Made to be run only as CLI.  More useful is seperate functions for gathing data from html file as dict and then converting to json or not etc.  The CLI should be under "if __name__ == '__main__':   And there is no real purpose in putting mongo input file format into the same utility imho.  Larger need is for parser for the file format into something pythonic.  Of course I can extract such from this but be nicer if there was no need.

**Comment by jhh** [comment]
This was really a throw-away single use project so I will not be devoting time to working on it. I will, however, look at any pull requests.
